### ISSUE TITLE
implement iterative_process

### ISSUE THREAD

**Issue by flip40** [CS149-3/homework6#2]
This is the function called by the first 4 processes. This should generate a message "message #" for 30 seconds. It should sleep for a random time of 0, 1, or 2 seconds between messages.

This process should terminate after 30 seconds by exiting the function (don't end the process yourself).

Variables provided to the function:
process: integer for the process number (0, 1, 2, or 3)
pipe: the pipe that should be written to with write()
start_time: the start time in milliseconds of the parent process. Use this to determine how long the process has been running for your time stamp in messages (get_current_time() - start_time).

**Comment by FMock** [comment]
I'll work on iterative_process
